-- إنشاء الـ Schemas المتعددة في PostgreSQL
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS education;
CREATE SCHEMA IF NOT EXISTS assessment;
CREATE SCHEMA IF NOT EXISTS ai;
CREATE SCHEMA IF NOT EXISTS live;
CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS social;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS security;
CREATE SCHEMA IF NOT EXISTS system;

-- صلاحيات
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA education TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA assessment TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ai TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA live TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payments TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA social TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA security TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA system TO postgres;
